---
name: FlyCommand
main: IslandMCDevs/main
description: An advanced survival fly plugin!
version: 1.8.7
api:
- 3.0.0
author: IslandMCDevs
commands:
  fly:
    description: Command which allows flight when in Survival Mode!
permissions:
  fly.command:
    description: Fly command permission
    default: op
  fly.other:
    description: Allow you to activate fly for other players
    default: op
...
